version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - pip install --upgrade awscli
      - dotnet restore AspNetCoreWebApplication/AspNetCoreWebApplication.csproj
      - dotnet restore AspNetCoreWebApplicationTest/AspNetCoreWebApplicationTest.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output nhom3project/API.csproj
artifacts:
  files:
    - nhom3project/build_output/**/*
    - scripts/**/*
    - appspec.yml